In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
import torch

In [3]:
print(torch.__version__)

2.9.1+cu128


Intro to tensors 

In [4]:
#Creating Tensors
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [5]:
#tenosr as int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR2 = torch.tensor([[[[1,2,3],[3,6,9],[2,4,5]],
                         [[1,2,3],[3,6,9],[2,4,5]],
                         [[1,2,3],[3,6,9],[2,4,5]],
                         [[1,2,3],[3,6,9],[2,4,5]]]])

In [16]:
TENSOR2.ndim

4

In [17]:
TENSOR2.shape

torch.Size([1, 4, 3, 3])

In [18]:
TENSOR2_direct = torch.tensor([
    
    [
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 0: 3 rows, 4 elements each
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 1
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 2
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]]   # Slice 3
    ],
    [
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 0
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 1
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 2
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]]   # Slice 3
    ]
])

print(TENSOR2_direct.shape)  

torch.Size([2, 4, 3, 4])


In [19]:
TENSOR2_direct.ndim

4

In [20]:
## Random Tensors
random_tensor = torch.rand(10, 10,10)
random_tensor

tensor([[[0.0501, 0.6525, 0.5939, 0.6133, 0.3408, 0.6600, 0.3303, 0.6444,
          0.0358, 0.0583],
         [0.8530, 0.3183, 0.5638, 0.9508, 0.9062, 0.4482, 0.3532, 0.4752,
          0.0308, 0.9454],
         [0.2496, 0.7142, 0.6574, 0.8872, 0.0020, 0.1984, 0.0769, 0.3901,
          0.1898, 0.7597],
         [0.3621, 0.4494, 0.1922, 0.9606, 0.9086, 0.4457, 0.9683, 0.6835,
          0.3098, 0.1074],
         [0.1155, 0.2237, 0.7548, 0.0159, 0.4979, 0.6105, 0.5437, 0.1246,
          0.1562, 0.8935],
         [0.4351, 0.2681, 0.2219, 0.2885, 0.0721, 0.3043, 0.5886, 0.2402,
          0.4157, 0.4431],
         [0.4887, 0.5400, 0.4494, 0.8672, 0.7415, 0.5642, 0.4274, 0.1006,
          0.7754, 0.7759],
         [0.9258, 0.3474, 0.9698, 0.9222, 0.2482, 0.4972, 0.9982, 0.3979,
          0.0342, 0.4451],
         [0.6296, 0.5502, 0.1344, 0.7967, 0.9164, 0.4591, 0.9555, 0.2093,
          0.0313, 0.8555],
         [0.7553, 0.4180, 0.0167, 0.8954, 0.1093, 0.8016, 0.0900, 0.8200,
          0.5582,

In [21]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([10, 10, 10])

In [23]:
random_tensor2 = torch.rand(1,3,4,5)
random_tensor2

tensor([[[[0.5940, 0.1871, 0.3472, 0.1934, 0.3377],
          [0.8129, 0.8717, 0.7748, 0.5745, 0.7388],
          [0.5760, 0.8212, 0.9615, 0.6450, 0.0233],
          [0.7158, 0.3127, 0.3877, 0.7101, 0.7880]],

         [[0.8785, 0.9701, 0.4812, 0.2444, 0.9764],
          [0.1333, 0.2287, 0.3274, 0.3030, 0.3662],
          [0.8209, 0.7895, 0.8284, 0.9350, 0.6456],
          [0.7906, 0.7240, 0.3547, 0.2852, 0.7611]],

         [[0.0562, 0.6502, 0.0128, 0.0982, 0.3698],
          [0.9876, 0.0050, 0.0133, 0.5907, 0.0817],
          [0.3190, 0.6015, 0.6317, 0.3384, 0.1028],
          [0.7131, 0.6588, 0.4358, 0.5760, 0.0537]]]])

In [24]:
random_tensor2.ndim

4

In [25]:
## replication image tensosr
random_image_size_tensor = torch.rand(size = (3,224,224)) #height, weidht,colors
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [26]:
## zeros and ones tensor
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

In [29]:
## creating range of tensors
one_to_10 = torch.arange(start = 0,end = 1000, step =20)

In [30]:
one_to_10

tensor([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200, 220, 240, 260,
        280, 300, 320, 340, 360, 380, 400, 420, 440, 460, 480, 500, 520, 540,
        560, 580, 600, 620, 640, 660, 680, 700, 720, 740, 760, 780, 800, 820,
        840, 860, 880, 900, 920, 940, 960, 980])

In [31]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_10)

In [32]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

In [33]:
# Tensor data types

In [35]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, #datatype of tensor 
                               device = "cuda",
                               requires_grad= False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [36]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [37]:
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [38]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [39]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)

In [48]:
some_tensor = torch.rand(3, 4, dtype=torch.float16)
some_tensor

tensor([[0.9824, 0.2588, 0.7515, 0.3257],
        [0.6685, 0.4131, 0.1797, 0.4053],
        [0.8218, 0.7021, 0.0640, 0.4570]], dtype=torch.float16)

In [49]:
print("Find details")
print(some_tensor)
print(f"datatype of tenosr: {some_tensor.dtype}")
print(f"shape of tenosr: {some_tensor.shape}")
print(f"tensor device:{some_tensor.device}")

Find details
tensor([[0.9824, 0.2588, 0.7515, 0.3257],
        [0.6685, 0.4131, 0.1797, 0.4053],
        [0.8218, 0.7021, 0.0640, 0.4570]], dtype=torch.float16)
datatype of tenosr: torch.float16
shape of tenosr: torch.Size([3, 4])
tensor device:cpu


Manipulating Tensors


In [57]:
#Tesnsor addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [54]:
tensor * 10

tensor([100, 200, 300])

In [58]:
tensor - 10

tensor([-9, -8, -7])

In [59]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [61]:
## Matrix Multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
torch.matmul(tensor, tensor) #1*1 + 2*2 + 3*3

tensor(14)

In [64]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.68 ms, sys: 146 μs, total: 1.82 ms
Wall time: 12.5 ms


In [65]:
%%time

torch.matmul(tensor, tensor)

CPU times: user 84 μs, sys: 93 μs, total: 177 μs
Wall time: 143 μs


tensor(14)

In [66]:
## Common erros in deep learning shape errors

In [ ]:
torch.matmul(torch.rand(5,3), torch.rand(3,2))
# if innner dimensions do not match then error and resultant matrix will be outer dimesnions ie, 5,2 in this case

tensor([[1.4171, 0.7981],
        [0.9061, 0.3201],
        [0.6108, 0.3150],
        [1.2097, 0.7187],
        [0.8924, 0.3100]])

In [76]:

# shapes for matrix multiplicaiton
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [77]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [79]:
tensor_B.T, tensor_B.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([3, 2]))

In [ ]:
torch.matmul(tensor_A,tensor_B.T)
#innner matches 

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])