In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
import torch

In [3]:
print(torch.__version__)

2.9.1+cu128


Intro to tensors 

In [4]:
#Creating Tensors
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [5]:
#tenosr as int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR2 = torch.tensor([[[[1,2,3],[3,6,9],[2,4,5]],
                         [[1,2,3],[3,6,9],[2,4,5]],
                         [[1,2,3],[3,6,9],[2,4,5]],
                         [[1,2,3],[3,6,9],[2,4,5]]]])

In [16]:
TENSOR2.ndim

4

In [17]:
TENSOR2.shape

torch.Size([1, 4, 3, 3])

In [18]:
TENSOR2_direct = torch.tensor([
    
    [
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 0: 3 rows, 4 elements each
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 1
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 2
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]]   # Slice 3
    ],
    [
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 0
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 1
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 2
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]]   # Slice 3
    ]
])

print(TENSOR2_direct.shape)  

torch.Size([2, 4, 3, 4])


In [19]:
TENSOR2_direct.ndim

4

In [20]:
## Random Tensors
random_tensor = torch.rand(10, 10,10)
random_tensor

tensor([[[1.1647e-02, 1.0926e-01, 4.3405e-01, 3.6199e-01, 9.7374e-01,
          9.0215e-01, 5.0649e-01, 5.7381e-04, 2.4708e-02, 3.6620e-01],
         [7.4319e-01, 9.9788e-01, 4.8139e-02, 9.7241e-01, 7.3643e-01,
          9.1279e-01, 1.3880e-01, 3.9694e-01, 1.6116e-01, 3.4506e-01],
         [8.3113e-01, 4.7301e-01, 1.6798e-01, 4.7402e-01, 9.2997e-01,
          2.7721e-01, 6.6035e-01, 3.8388e-01, 1.5408e-01, 7.4761e-01],
         [9.6650e-01, 5.5109e-01, 8.3262e-01, 8.1237e-02, 7.1230e-01,
          2.5664e-01, 2.9310e-01, 7.3194e-01, 2.5483e-01, 5.9046e-02],
         [7.5751e-01, 9.8253e-01, 6.7116e-01, 8.0531e-01, 4.4051e-01,
          2.7269e-01, 4.7529e-01, 3.5182e-01, 4.2478e-01, 7.5009e-01],
         [6.7856e-01, 6.6970e-01, 3.5857e-02, 7.2091e-01, 9.6229e-01,
          5.9600e-01, 8.4052e-01, 8.3323e-01, 9.2519e-01, 6.5580e-01],
         [7.1826e-02, 8.6167e-02, 5.3621e-01, 5.8024e-01, 7.3801e-01,
          9.9373e-01, 2.2929e-01, 5.2134e-01, 4.1546e-01, 6.4882e-01],
         [1.8

In [21]:
random_tensor.ndim

3

In [22]:
random_tensor.shape

torch.Size([10, 10, 10])

In [24]:
random_tensor2 = torch.rand(1,3,4,5)
random_tensor2

tensor([[[[0.0675, 0.6230, 0.7457, 0.7127, 0.0904],
          [0.6866, 0.1986, 0.9911, 0.7465, 0.8727],
          [0.4793, 0.5197, 0.7237, 0.1528, 0.5037],
          [0.6469, 0.4576, 0.7777, 0.8117, 0.8140]],

         [[0.4479, 0.4932, 0.7269, 0.3169, 0.8092],
          [0.5844, 0.6751, 0.6260, 0.7176, 0.2493],
          [0.8314, 0.2843, 0.0295, 0.9948, 0.5059],
          [0.9754, 0.5371, 0.3659, 0.8365, 0.7398]],

         [[0.7255, 0.7451, 0.3787, 0.4858, 0.2267],
          [0.5815, 0.3328, 0.0943, 0.3105, 0.4660],
          [0.6698, 0.1981, 0.0261, 0.5705, 0.2931],
          [0.8929, 0.9897, 0.4454, 0.2819, 0.5555]]]])

In [25]:
random_tensor2.ndim

4

In [29]:
## replication image tensosr
random_image_size_tensor = torch.rand(size = (3,224,224)) #height, weidht,colors
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [32]:
## zeros and ones tensor
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
ones.dtype

torch.float32

In [41]:
## creating range of tensors
one_to_10 = torch.arange(start = 0,end = 1000, step =20)

In [42]:
one_to_10

tensor([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200, 220, 240, 260,
        280, 300, 320, 340, 360, 380, 400, 420, 440, 460, 480, 500, 520, 540,
        560, 580, 600, 620, 640, 660, 680, 700, 720, 740, 760, 780, 800, 820,
        840, 860, 880, 900, 920, 940, 960, 980])

In [44]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_10)

In [45]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

In [46]:
# Tensor data types

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, #datatype of tensor 
                               device = "None",
                               requires_grad= False)
float_32_tensor

tensor([3., 6., 9.])

In [51]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [52]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [53]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])