In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import torch

In [2]:
print(torch.__version__)

2.9.1+cu128


Intro to tensors 

In [3]:
#Creating Tensors
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
#tenosr as int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR2 = torch.tensor([[[[1,2,3],[3,6,9],[2,4,5]],
                         [[1,2,3],[3,6,9],[2,4,5]],
                         [[1,2,3],[3,6,9],[2,4,5]],
                         [[1,2,3],[3,6,9],[2,4,5]]]])

In [15]:
TENSOR2.ndim

4

In [16]:
TENSOR2.shape

torch.Size([1, 4, 3, 3])

In [17]:
TENSOR2_direct = torch.tensor([
    
    [
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 0: 3 rows, 4 elements each
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 1
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 2
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]]   # Slice 3
    ],
    [
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 0
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 1
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]],  # Slice 2
        [[1,2,3,4], [3,6,9,4], [2,4,5,4]]   # Slice 3
    ]
])

print(TENSOR2_direct.shape)  

torch.Size([2, 4, 3, 4])


In [18]:
TENSOR2_direct.ndim

4

In [19]:
## Random Tensors
random_tensor = torch.rand(10, 10,10)
random_tensor

tensor([[[1.6375e-01, 7.9264e-01, 3.0692e-01, 8.7397e-02, 8.6178e-01,
          9.3864e-01, 3.3770e-02, 5.3262e-01, 2.2716e-01, 6.6166e-01],
         [6.8352e-01, 2.5500e-01, 9.4643e-01, 3.8658e-01, 8.8344e-01,
          7.1934e-01, 9.0411e-01, 1.0339e-01, 1.7205e-01, 9.5668e-01],
         [5.3102e-01, 9.0238e-01, 7.8581e-01, 8.8915e-02, 6.4606e-01,
          4.4324e-01, 3.0267e-01, 4.2490e-01, 8.1444e-02, 9.4589e-01],
         [1.1869e-01, 5.8558e-01, 9.2824e-01, 2.5284e-01, 6.1702e-01,
          8.4055e-01, 5.0720e-01, 1.6905e-01, 1.4773e-01, 2.8943e-01],
         [3.5414e-01, 3.4317e-01, 3.9735e-01, 4.5948e-01, 6.8543e-01,
          4.6275e-01, 7.6653e-01, 2.7675e-01, 8.5676e-01, 3.4526e-01],
         [1.5046e-01, 7.0564e-01, 3.4794e-01, 5.0108e-01, 9.8492e-01,
          7.6781e-01, 5.2687e-02, 7.3193e-01, 8.4698e-01, 6.4839e-01],
         [7.1833e-01, 9.9375e-01, 9.6652e-01, 6.7137e-01, 6.3516e-01,
          1.2244e-02, 1.1362e-01, 9.5518e-03, 7.1583e-01, 3.2721e-01],
         [3.0

In [20]:
random_tensor.ndim

3

In [21]:
random_tensor.shape

torch.Size([10, 10, 10])

In [22]:
random_tensor2 = torch.rand(1,3,4,5)
random_tensor2

tensor([[[[0.3837, 0.5839, 0.4681, 0.3338, 0.1062],
          [0.2586, 0.5664, 0.5083, 0.0070, 0.2366],
          [0.5524, 0.0159, 0.2514, 0.7719, 0.8316],
          [0.6397, 0.2971, 0.3414, 0.4259, 0.8479]],

         [[0.9572, 0.4888, 0.3736, 0.6566, 0.1400],
          [0.1535, 0.5154, 0.1056, 0.5756, 0.9022],
          [0.5206, 0.0875, 0.3732, 0.5972, 0.6280],
          [0.2317, 0.7701, 0.5291, 0.7656, 0.0378]],

         [[0.6995, 0.0926, 0.2684, 0.7076, 0.3918],
          [0.0367, 0.5560, 0.6442, 0.0424, 0.7902],
          [0.7643, 0.0482, 0.4851, 0.5558, 0.2425],
          [0.9892, 0.3126, 0.3263, 0.9524, 0.0037]]]])

In [23]:
random_tensor2.ndim

4

In [24]:
## replication image tensosr
random_image_size_tensor = torch.rand(size = (3,224,224)) #height, weidht,colors
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [25]:
## zeros and ones tensor
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

In [28]:
## creating range of tensors
one_to_10 = torch.arange(start = 0,end = 1000, step =20)

In [29]:
one_to_10

tensor([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200, 220, 240, 260,
        280, 300, 320, 340, 360, 380, 400, 420, 440, 460, 480, 500, 520, 540,
        560, 580, 600, 620, 640, 660, 680, 700, 720, 740, 760, 780, 800, 820,
        840, 860, 880, 900, 920, 940, 960, 980])

In [30]:
#creating tensors like
ten_zeros = torch.zeros_like(input=one_to_10)

In [31]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

In [32]:
# Tensor data types

In [33]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None, #datatype of tensor 
                               device = "cuda",
                               requires_grad= False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [35]:
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [36]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [37]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)

In [38]:
some_tensor = torch.rand(3, 4, dtype=torch.float16)
some_tensor

tensor([[0.0913, 0.4819, 0.6963, 0.2139],
        [0.0156, 0.9692, 0.6348, 0.8853],
        [0.8340, 0.2339, 0.5391, 0.9336]], dtype=torch.float16)

In [39]:
print("Find details")
print(some_tensor)
print(f"datatype of tenosr: {some_tensor.dtype}")
print(f"shape of tenosr: {some_tensor.shape}")
print(f"tensor device:{some_tensor.device}")

Find details
tensor([[0.0913, 0.4819, 0.6963, 0.2139],
        [0.0156, 0.9692, 0.6348, 0.8853],
        [0.8340, 0.2339, 0.5391, 0.9336]], dtype=torch.float16)
datatype of tenosr: torch.float16
shape of tenosr: torch.Size([3, 4])
tensor device:cpu


Manipulating Tensors


In [40]:
#Tesnsor addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [41]:
tensor * 10

tensor([10, 20, 30])

In [42]:
tensor - 10

tensor([-9, -8, -7])

In [43]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [44]:
## Matrix Multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [45]:
torch.matmul(tensor, tensor) #1*1 + 2*2 + 3*3

tensor(14)

In [46]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.06 ms, sys: 17 μs, total: 1.08 ms
Wall time: 1.48 ms


In [47]:
%%time

torch.matmul(tensor, tensor)

CPU times: user 223 μs, sys: 108 μs, total: 331 μs
Wall time: 210 μs


tensor(14)

In [48]:
## Common erros in deep learning shape errors

In [49]:
torch.matmul(torch.rand(5,3), torch.rand(3,2))
# if innner dimensions do not match then error and resultant matrix will be outer dimesnions ie, 5,2 in this case

tensor([[0.3080, 0.2202],
        [0.5896, 0.3167],
        [0.5473, 0.1707],
        [0.4623, 0.2838],
        [0.5164, 0.2519]])

In [57]:

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])


In [58]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [59]:
tensor_B.T, tensor_B.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([3, 2]))

In [60]:
torch.matmul(tensor_A,tensor_B.T)
#innner matches 

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Tensor Aggregation(min,max,mean,sum etc)

In [61]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [62]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [63]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [64]:
x.type(torch.float32)

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [65]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [66]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Postional min and max

In [67]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [68]:
x.argmin(), torch.argmin(x)
#find the postion of tenosr with minimum value index

(tensor(0), tensor(0))

In [69]:
x.argmax()
#find the postion of tensor with maximum value index

tensor(9)

Reshaping, stacking, squeezing and unsqueezing tensor

In [70]:
y = torch.arange(1.,10.)
y, y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [71]:
y_reshaped = y.reshape(3,3)
y_reshaped, y_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [72]:
# Original tensor with multiple dimensions
tensor_3d = torch.rand(2, 3, 4)  # 2 × 3 × 4 = 24 elements total

# Valid reshapes (all have 24 elements):
tensor_3d, tensor_3d.reshape(24),tensor_3d.reshape(6, 4), tensor_3d.reshape(4, 1, 6),tensor_3d.reshape(1, 24, 1)     # 3D: 1 × 24 × 1 = 24 ✓



(tensor([[[0.9219, 0.5944, 0.5706, 0.0317],
          [0.5854, 0.5972, 0.3995, 0.7105],
          [0.5616, 0.2716, 0.1048, 0.1865]],
 
         [[0.3227, 0.2969, 0.9811, 0.9340],
          [0.5574, 0.0114, 0.1087, 0.5588],
          [0.2820, 0.8917, 0.1475, 0.9108]]]),
 tensor([0.9219, 0.5944, 0.5706, 0.0317, 0.5854, 0.5972, 0.3995, 0.7105, 0.5616,
         0.2716, 0.1048, 0.1865, 0.3227, 0.2969, 0.9811, 0.9340, 0.5574, 0.0114,
         0.1087, 0.5588, 0.2820, 0.8917, 0.1475, 0.9108]),
 tensor([[0.9219, 0.5944, 0.5706, 0.0317],
         [0.5854, 0.5972, 0.3995, 0.7105],
         [0.5616, 0.2716, 0.1048, 0.1865],
         [0.3227, 0.2969, 0.9811, 0.9340],
         [0.5574, 0.0114, 0.1087, 0.5588],
         [0.2820, 0.8917, 0.1475, 0.9108]]),
 tensor([[[0.9219, 0.5944, 0.5706, 0.0317, 0.5854, 0.5972]],
 
         [[0.3995, 0.7105, 0.5616, 0.2716, 0.1048, 0.1865]],
 
         [[0.3227, 0.2969, 0.9811, 0.9340, 0.5574, 0.0114]],
 
         [[0.1087, 0.5588, 0.2820, 0.8917, 0.1475, 0.9108]]]

In [73]:
tensor_3d.ndim, tensor_3d.reshape(24).ndim, tensor_3d.reshape(6, 4).ndim, tensor_3d.reshape(4, 2, 3).ndim, tensor_3d.reshape(1, 24, 1).ndim

(3, 1, 2, 3, 3)

In [74]:
# Use view
z = y.view(1,9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [75]:
#Stacking
x_stack = torch.stack([x,x,x,x])
x_stack

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [76]:
#Stacking
x_stack = torch.stack([x,x,x,x],dim = 1)
x_stack

tensor([[ 0,  0,  0,  0],
        [10, 10, 10, 10],
        [20, 20, 20, 20],
        [30, 30, 30, 30],
        [40, 40, 40, 40],
        [50, 50, 50, 50],
        [60, 60, 60, 60],
        [70, 70, 70, 70],
        [80, 80, 80, 80],
        [90, 90, 90, 90]])

In [77]:
x_stack = torch.vstack([x,x,x,x])
x_stack

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [78]:
x_stack = torch.hstack([x,x,x,x])
x_stack

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90,  0, 10, 20, 30, 40, 50, 60, 70,
        80, 90,  0, 10, 20, 30, 40, 50, 60, 70, 80, 90,  0, 10, 20, 30, 40, 50,
        60, 70, 80, 90])

In [79]:
a = torch.tensor([[1, 2], [3, 4]])  # shape: (2, 2)

torch.stack([a, a])      # shape: (2, 2, 2) - new dimension added


tensor([[[1, 2],
         [3, 4]],

        [[1, 2],
         [3, 4]]])

In [80]:
torch.vstack([a, a])     # shape: (4, 2) - stacked vertically


tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])

In [81]:
torch.hstack([a, a])     # shape: (2, 4) - stacked horizontally

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4]])

In [82]:
y.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [83]:
y_new = torch.zeros(2,1,4,1)
y_new,y_new.shape

(tensor([[[[0.],
           [0.],
           [0.],
           [0.]]],
 
 
         [[[0.],
           [0.],
           [0.],
           [0.]]]]),
 torch.Size([2, 1, 4, 1]))

In [84]:
y_new1 = y_new.squeeze()
y_new1,y_new1.shape

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Size([2, 4]))

In [85]:
y_new1.unsqueeze(0).shape

torch.Size([1, 2, 4])

In [86]:
#permute
x_orginal = torch.rand(size=(224,224,3))
#premute the original tenosr to rearrange the dims
x_permuted = x_orginal.permute(2,0,1) #shifts axis zero to 1 1 to 2 and 2 to 0
print(F"previous shape: {x_orginal.shape}")
print(f"x permuted: {x_permuted.shape}")

previous shape: torch.Size([224, 224, 3])
x permuted: torch.Size([3, 224, 224])


In [87]:
x_permuted2 = x_orginal.permute(2,1,0) #shifts axis zero to 1 1 to 2 and 2 to 0
x_permuted2.shape

torch.Size([3, 224, 224])

In [88]:
x_orginal.shape

torch.Size([224, 224, 3])

In [89]:
#Indexing
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [90]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [91]:
x[0,0]

tensor([1, 2, 3])

In [92]:
x[0,0,0]

tensor(1)

In [93]:
x[0,2,2]

tensor(9)

In [94]:
x[:,0]

tensor([[1, 2, 3]])

In [95]:
x [:,:,1]

tensor([[2, 5, 8]])

In [96]:
x [:,1,1]

tensor([5])

In [97]:
x[:,2,2]

tensor([9])

Pytorch and numpy

In [99]:
array = np.arange(1.0,8.0)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [102]:
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [104]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [105]:
tensor = torch.ones(7)
numpy_tenosr = tensor.numpy()
tensor, numpy_tenosr

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [106]:
tensor = tensor + 1
numpy_tenosr

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)